Update README
wearefrank/ladybug pull request #217
Opened 2024-03-05 10:13 UTC by MatthijsSmets

Angular.json was updated in [ladybug-frontend](https://github.com/wearefrank/ladybug-frontend) which requires an update to the README.md

2024-03-05 10:53 UTC, philipsens commented on README.md
> +# Ladybug debug- and test tool by WeAreFrank!
Wrong grammar, this isn't dutch.
Should be 'debug and test tool'

Is there a reason to change all the syntax of the headers?

2024-03-05 10:55 UTC, philipsens commented on README.md
> +- Install [Node.js](https://nodejs.org/en/), choose version 16. You should get executables `npm` version 8.x and `node` version 16.x. Check these versions using `npm -v` and `node -v`.
Is there a reason to change the syntax of the list items?

2024-03-05 10:57 UTC, MatthijsSmets commented on README.md
> +# Ladybug debug- and test tool by WeAreFrank!
I did not change this, let me check how this happened

2024-03-05 10:57 UTC, philipsens requested changes
It's hard to review the changes will all the changed syntax, and indent. 

I'd suggest to put it back.

2024-03-05 14:54 UTC, mhdirkse commented on README.md
>  - Run the command `ng build`, to build the current project
I have to do `yarn ng build` instead of just `ng build`.

2024-03-05 15:00 UTC, mhdirkse commented on README.md
>  - In the `dist/ladybug/index.html` change the types of the three scripts on line 15 to `application/javascript` (so `type="module"` -> `type="application/javascript"`). The specific scripts are:
On my computer it turned out to be line 14.

2024-03-05 15:31 UTC, mhdirkse requested changes
You need `npm publish -otp=<code from authenticator app of your telephone>`

2024-03-05 17:16 UTC, MatthijsSmets commented
> You need `npm publish -otp=<code from authenticator app of your telephone>`

This is not the case for every user, it depends on if you have 2FA enabled.

2024-03-05 17:19 UTC, MatthijsSmets commented on README.md
>  - Run the command `ng build`, to build the current project
That means your angular cli is not installed properly, this still works for anyone that has it installed correctly.
This is also something that was not changed in this pr.

2024-03-06 10:56 UTC, philipsens approved these changes

2024-03-07 16:45 UTC, jacodg approved these changes

2024-03-07 16:46 UTC, merged