Do not encode booleans with XMLEncoder
wearefrank/ladybug pull request #306
Opened 2024-09-23 11:45 UTC by mhdirkse

2024-09-23 12:12 UTC, mhdirkse commented
Ik vertrouw dit niet helemaal. Maar ik heb gezien dat het success checkpoint in mijn test nu "true" laat zien, geen XML code. Dat was tenminste zo een paar commits geleden. Sindsdien heb ik een paar dingen toegevoegd...

2024-09-24 12:33 UTC, nielsm5 requested changes

2024-09-24 12:33 UTC, nielsm5 commented on src/main/java/nl/nn/testtool/MessageEncoderImpl.java
> +	private static final Logger log = LoggerFactory.getLogger(MethodHandles.lookup().lookupClass());
Dit is zonde, je weet immers de classname al...

2024-09-24 12:33 UTC, nielsm5 commented on src/main/java/nl/nn/testtool/MessageEncoderImpl.java
> +				toStringResult = new ToStringResult(Boolean.toString((Boolean) message), null, Boolean.class.getName());
Gewoon direct returnen toch?

2024-09-24 12:33 UTC, nielsm5 commented on src/main/java/nl/nn/testtool/MessageEncoderImpl.java
> +					return (T) rawResult;
Direct returnen.

2024-12-10 09:20 UTC, mhdirkse commented
Dit ga ik niet afmaken. Hebben we toen uitgebreid over gepraat.

2024-12-10 09:20 UTC, closed without merging